'use strict'

module.exports = {
  rules: {
    'comma-dangle': [ 'error', 'always-multiline' ],
    'no-cond-assign': [ 'error', 'except-parens' ],
    'no-console': 'warn',
    'no-constant-condition': 'error',
    'no-control-regex': 'error',
    'no-debugger': 'error',
    'no-dupe-args': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-empty': 'error',
    'no-empty-character-class': 'error',
    'no-ex-assign': 'error',
    'no-extra-boolean-cast': 'error',
    'no-extra-parens': [ 'off' ],
    'no-extra-semi': 'error',
    'no-func-assign': 'error',
    'no-inner-declarations': 'error',
    'no-invalid-regexp': 'error',
    'no-irregular-whitespace': 'error',
    'no-obj-calls': 'error',
    'no-prototype-builtins': 'error',
    'no-regex-spaces': 'error',
    'no-sparse-arrays': 'error',
    'no-template-curly-in-string': 'error',
    'no-unexpected-multiline': 'error',
    'no-unreachable': 'error',
    'no-unsafe-finally': 'error',
    'no-unsafe-negation': 'error',
    'use-isnan': 'error',
    'valid-jsdoc': [ 'warn', {
      prefer: {
        returns: 'returns',
      },
      requireReturn: true,
      requireParamDescription: true,
      requireReturnDescription: true,
      requireReturnType: true,
    }],
    'valid-typeof': 'error',
    'accessor-pairs': 'error',
    'array-callback-return': 'error',
    'block-scoped-var': 'error',
    'class-methods-use-this': 'warn',
    'complexity': [ 'error', 11 ],
    'consistent-return': 'error',
    'curly': [ 'error', 'multi-line' ],
    'default-case': 'error',
    'dot-location': [ 'error', 'property' ],
    'dot-notation': 'error',
    'eqeqeq': [ 'error', 'allow-null' ],
    'guard-for-in': 'error',
    'no-alert': 'error',
    'no-caller': 'error',
    'no-case-declarations': 'error',
    'no-div-regex': 'error',
    'no-else-return': 'error',
    'no-empty-function': 'error',
    'no-empty-pattern': 'error',
    'no-eq-null': 'off',
    'no-eval': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-extra-label': 'error',
    'no-fallthrough': 'off',
    'no-floating-decimal': 'error',
    'no-global-assign': 'error',
    'no-implicit-coercion': 'error',
    'no-implicit-globals': 'error',
    'no-implied-eval': 'error',
    'no-invalid-this': 'error',
    'no-iterator': 'error',
    'no-labels': 'error',
    'no-lone-blocks': 'error',
    'no-loop-func': 'error',
    'no-magic-numbers': 'off',
    'no-multi-spaces': 'error',
    'no-multi-str': 'error',
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-wrappers': 'error',
    'no-octal': 'error',
    'no-octal-escape': 'error',
    'no-param-reassign': 'off',
    'no-process-env': 'off',
    'no-proto': 'error',
    'no-redeclare': 'error',
    'no-restricted-properties': 'off',
    'no-return-assign': [ 'error', 'except-parens' ],
    'no-return-await': 'error',
    'no-script-url': 'error',
    'no-self-assign': 'error',
    'no-self-compare': 'error',
    'no-sequences': 'error',
    'no-throw-literal': 'error',
    'no-unmodified-loop-condition': 'error',
    'no-unused-expressions': 'error',
    'no-unused-labels': 'error',
    'no-useless-call': 'error',
    'no-useless-concat': 'error',
    'no-useless-escape': 'error',
    'no-useless-return': 'error',
    'no-void': 'error',
    'no-warning-comments': 'warn',
    'no-with': 'error',
    'radix': 'error',
    'vars-on-top': 'error',
    'wrap-iife': [ 'error', 'inside' ],
    'yoda': 'warn',
    'strict': [ 'error', 'safe' ],
    'init-declarations': 'off',
    'no-catch-shadow': 'error',
    'no-delete-var': 'error',
    'no-label-var': 'error',
    'no-restricted-globals': 'error',
    'no-shadow': 'error',
    'no-shadow-restricted-names': 'error',
    'no-undef': 'error',
    'no-undef-init': 'off',
    'no-undefined': 'error',
    'no-unused-vars': 'error',
    'no-use-before-define': [ 'error', {
      functions: false,
    }],
    'callback-return': 'error',
    'global-require': 'error',
    'handle-callback-err': 'error',
    'no-mixed-requires': 'error',
    'no-new-require': 'error',
    'no-path-concat': 'error',
    'no-process-exit': 'error',
    'no-restricted-imports': 'off',
    'no-restricted-modules': 'off',
    'no-sync': 'error',
    'array-bracket-spacing': [ 'error', 'always', {
      singleValue: true,
      arraysInArrays: false,
      objectsInArrays: false,
    }],
    'block-spacing': 'error',
    'brace-style': [ 'error', 'stroustrup', { allowSingleLine: true }],
    'camelcase': 'error',
    'comma-spacing': 'error',
    'comma-style': 'off',
    'computed-property-spacing': 'error',
    'consistent-this': [ 'error', 'that', 'self' ],
    'eol-last': 'error',
    'func-call-spacing': [ 'error', 'never' ],
    'func-name-matching': 'error',
    'func-names': 'off',
    'func-style': [ 'error', 'declaration', { allowArrowFunctions: true }],
    'id-blacklist': 'off',
    'id-length': 'off',
    'id-match': 'off',
    'indent': [ 'error', 2 ],
    'jsx-quotes': [ 'error', 'prefer-double' ],
    'key-spacing': 'error',
    'keyword-spacing': 'error',
    'line-comment-position': 'off',
    'linebreak-style': 'error',
    'lines-around-comment': 'off',
    'lines-around-directive': 'error',
    'max-depth': [ 'error', 4 ],
    'max-len': [ 'error', {
      code: 80,
      tabWidth: 2,
      ignoreUrls: true,
      ignoreTrailingComments: true,
    }],
    'max-lines': 'off',
    'max-nested-callbacks': [ 'error', 4 ],
    'max-params': [ 'error', 4 ],
    'max-statements-per-line': [ 'error', { max: 3 }],
    'max-statements': [ 'error', 11 ],
    'multiline-ternary': 'off',
    'new-cap': 'error',
    'new-parens': 'error',
    'newline-after-var': 'off',
    'newline-before-return': 'off',
    'newline-per-chained-call': 'error',
    'no-array-constructor': 'error',
    'no-bitwise': 'error',
    'no-continue': 'error',
    'no-inline-comments': 'off',
    'no-lonely-if': 'error',
    'no-mixed-operators': 'error',
    'no-mixed-spaces-and-tabs': 'error',
    'no-multiple-empty-lines': [ 'error', { max: 2 }],
    'no-negated-condition': 'warn',
    'no-nested-ternary': 'error',
    'no-new-object': 'error',
    'no-plusplus': 'off',
    'no-restricted-syntax': [ 'error', 'WithStatement' ],
    'no-tabs': 'error',
    'no-ternary': 'off',
    'no-trailing-spaces': 'error',
    'no-underscore-dangle': 'off',
    'no-unneeded-ternary': 'error',
    'no-whitespace-before-property': 'error',
    'object-curly-newline': 'off',
    'object-curly-spacing': [ 'error', 'always', {
      objectsInObjects: false,
      arraysInObjects: false,
    }],
    'object-property-newline': [ 'error', {
      allowMultiplePropertiesPerLine: true,
    }],
    'one-var': [ 'error', {
      uninitialized: 'always',
      initialized: 'never',
    }],
    'one-var-declaration-per-line': [ 'error', 'initializations' ],
    'operator-assignment': [ 'error', 'always' ],
    'operator-linebreak': [ 'error', 'before' ],
    'padded-blocks': 'off',
    'quote-props': [ 'error', 'consistent-as-needed' ],
    'quotes': [ 'error', 'single' ],
    'require-jsdoc': 'off',
    'semi': [ 'error', 'never' ],
    'sort-keys': 'off',
    'semi-spacing': 'error',
    'sort-imports': 'off',
    'sort-vars': 'off',
    'space-before-blocks': 'off',
    'space-before-function-paren': [ 'error', 'never' ],
    'space-in-parens': [ 'error', 'never' ],
    'space-infix-ops': 'error',
    'space-unary-ops': 'error',
    'spaced-comment': [ 'error', 'always' ],
    'unicode-bom': 'error',
    'wrap-regex': 'error',
    'arrow-body-style': 'off',
    'arrow-parens': [ 'error', 'always' ],
    'arrow-spacing': 'error',
    'constructor-super': 'error',
    'generator-star-spacing': [ 'error', 'after' ],
    'no-class-assign': 'error',
    'no-confusing-arrow': 'error',
    'no-const-assign': 'error',
    'no-dupe-class-members': 'error',
    'no-duplicate-imports': 'off',
    'no-new-symbol': 'error',
    'no-this-before-super': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-constructor': 'error',
    'no-useless-rename': 'error',
    'no-var': 'error',
    'object-shorthand': 'error',
    'prefer-arrow-callback': 'error',
    'prefer-const': 'error',
    'prefer-numeric-literals': 'off',
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'error',
    'require-yield': 'error',
    'rest-spread-spacing': 'error',
    'symbol-description': 'error',
    'template-curly-spacing': 'error',
    'yield-star-spacing': 'error',
  },
}
