'use strict'

module.exports = {
  parserOptions: {
    sourceType: 'module',
    ecmaFeatures: {
      impliedStrict: false
    }
  },
  rules: {
    'comma-dangle': [ 2, 'never' ],
    'no-cond-assign': [ 2, 'except-parens' ],
    'no-console': 1,
    'no-contant-condition': 2,
    'no-control-regex': 2,
    'no-debugger': 2,
    'no-dupe-args': 2,
    'no-dupe-keys': 2,
    'no-duplicate-case': 2,
    'no-empty': 2,
    'no-empty-character-class': 2,
    'no-ex-assign': 2,
    'no-extra-boolean-cast': 2,
    'no-extra-parens': [ 2, 'all', {
      conditionalAssign: true
    }],
    'no-extra-semi': 2,
    'no-func-assign': 2,
    'no-inner-declarations': 2,
    'no-invalid-regexp': 2,
    'no-irregular-whitespace': 2,
    'no-negated-in-lhs': 2,
    'no-obj-calls': 2,
    'no-regex-spaces': 2,
    'no-sparse-arrays': 2,
    'no-unexpected-multiline': 2,
    'no-unreachable': 2,
    'use-isnan': 2,
    'valid-jsdoc': [ 1, {
      prefer: {
        returns: 'returns'
      },
      requireReturn: true,
      requireParamDescription: true,
      requireReturnDescription: true,
      requireReturnType: true
    }],
    'valid-typeof': 2,
    'accessor-pairs': 1,
    'array-callback-return': 2,
    'block-scoped-var': 1,
    'complexity': [ 2, 11 ],
    'consistent-return': 1,
    'curly': [ 2, 'multi' ],
    'default-case': 1,
    'dot-location': [ 2, 'property' ],
    'dot-notation': 1,
    'eqeqeq': [ 2, 'allow-null' ],
    'guard-for-in': 2,
    'no-alert': 1,
    'no-caller': 2,
    'no-case-declarations': 2,
    'no-div-regex': 2,
    'no-else-return': 1,
    'no-empty-function': 1,
    'no-empty-pattern': 2,
    'no-eq-null': 0,
    'no-eval': 2,
    'no-extend-native': 2,
    'no-extra-bind': 2,
    'no-extra-label': 2,
    'no-fallthrough': 0,
    'no-floating-decimal': 1,
    'no-implicit-coercion': 1,
    'no-implicit-globals': 2,
    'no-implied-eval': 2,
    'no-invalid-this': 1,
    'no-iterator': 2,
    'no-labels': 2,
    'no-lone-blocks': 2,
    'no-loop-func': 2,
    'no-magic-numbers': 0,
    'no-multi-spaces': 1,
    'no-multi-str': 2,
    'no-native-reassign': 2,
    'no-new': 2,
    'no-new-func': 2,
    'no-new-wrappers': 2,
    'no-octal': 2,
    'no-octal-escape': 2,
    'no-param-reassign': 0,
    'no-process-env': 0,
    'no-proto': 2,
    'no-redeclare': 2,
    'no-return-assign': [ 2, 'except-parens' ],
    'no-script-url': 2,
    'no-self-assign': 2,
    'no-self-compare': 1,
    'no-sequences': 2,
    'no-throw-literal': 2,
    'no-unmodified-loop-condition': 2,
    'no-unused-expressions': 2,
    'no-unused-labels': 2,
    'no-useless-call': 1,
    'no-useless-concat': 1,
    'no-void': 2,
    'no-warning-comments': 1,
    'no-with': 2,
    'radix': 1,
    'vars-on-top': 1,
    'wrap-iife': [ 1, 'inside' ],
    'yoda': 1,
    'strict': 2,
    'init-declarations': 0,
    'no-catch-shadow': 2,
    'no-delete-var': 2,
    'no-label-var': 2,
    'no-restricted-globals': 2,
    'no-shadow': 1,
    'no-shadow-restricted-names': 2,
    'no-undef': 2,
    'no-undef-init': 0,
    'no-undefined': 2,
    'no-unused-vars': 1,
    'no-use-before-define': 2,
    'callback-return': 1,
    'global-require': 1,
    'handle-callback-err': 2,
    'no-mixed-requires': 1,
    'no-new-require': 2,
    'no-path-concat': 1,
    'no-process-exit': 1,
    'no-restricted-imports': 0,
    'no-restricted-modules': 0,
    'no-sync': 1,
    'array-bracket-spacing': [ 1, 'always', {
      'singleValue': false,
      'arraysInArrays': false,
      'objectsInArrays': false
    }],
    'block-spacing': 1,
    'brace-style': [ 1, '1tbs', { 'allowSingleLine': true }],
    'camelcase': 1,
    'comma-spacing': 1,
    'comma-style': 0,
    'computed-property-spacing': 1,
    'consistent-this': [ 1, 'that', 'self' ],
    'eol-last': 2,
    'func-names': 0,
    'func-style': [ 1, 'declaration' ],
    'id-blacklist': 0,
    'id-length': 0,
    'id-match': 0,
    'indent': [ 2, 2 ],
    'jsx-quotes': [ 2, 'prefer-double' ],
    'key-spacing': 2,
    'keyword-spacing': 2,
    'linebreak-style': 2,
    'lines-around-comment': 0,
    'max-depth': [ 1, 4 ],
    'max-len': [ 1, {
      'code': 80,
      'tabWidth': 2,
      'ignoreUrls': true,
      'ignoreTrailingComments': true
    }],
    'max-nested-callbacks': [ 2, 4 ],
    'max-params': [ 1, 4 ],
    'max-statements': [ 1, 11 ],
    'new-cap': 2,
    'new-parens': 2,
    'newline-after-var': 1,
    'newline-before-return': 0,
    'newline-per-chained-call': 1,
    'no-array-constructor': 2,
    'no-bitwise': 2,
    'no-continue': 2,
    'no-inline-comments': 0,
    'no-lonely-if': 2,
    'no-mixed-spaces-and-tabs': 2,
    'no-multiple-empty-lines': [ 1, { 'max': 2 }],
    'no-negated-condition': 1,
    'no-nested-ternary': 2,
    'no-new-object': 2,
    'no-plusplus': 0,
    'no-restricted-syntax': [ 2, 'WithStatement' ],
    'no-spaced-func': 1,
    'no-ternary': 0,
    'no-trailing-spaces': 1,
    'no-underscore-dangle': 1,
    'no-unneeded-ternary': 2,
    'no-whitespace-before-property': 2,
    'object-curly-spacing': [ 2, 'always', {
      'objectsInObjects': false,
      'arraysInObjects': false
    }],
    'one-var': [ 2, 'never' ],
    'one-var-declaration-per-line': [ 2, 'initializations' ],
    'operator-assignment': [ 1, 'always' ],
    'operator-linebreak': [ 1, 'before' ],
    'padded-blocks': 0,
    'quote-props': [ 2, 'as-needed' ],
    'quotes': [ 2, 'single' ],
    'require-jsdoc': 0,
    'semi': [ 2, 'never' ],
    'semi-spacing': 2,
    'sort-imports': 0,
    'sort-vars': 0,
    'space-before-blocks': 0,
    'space-before-function-paren': [ 2, 'never' ],
    'space-in-parens': [ 1, 'never' ],
    'space-infix-ops': 2,
    'space-unary-ops': 1,
    'spaced-comment': [ 1, 'always' ],
    'wrap-regex': 1,
    'arrow-body-style': [ 2, 'as-needed' ],
    'arrow-parens': [ 1, 'always' ],
    'arrow-spacing': 1,
    'constructor-super': 2,
    'generator-star-spacing': 2,
    'no-class-assign': 2,
    'no-confusing-arrow': 1,
    'no-const-assign': 2,
    'no-dupe-class-members': 2,
    'no-new-symbol': 2,
    'no-this-before-super': 2,
    'no-useless-constructor': 1,
    'no-var': 2,
    'object-shorthand': 1,
    'prefer-arrow-callback': 1,
    'prefer-const': 1,
    'prefer-reflect': 1,
    'prefer-rest-params': 2,
    'prefer-spread': 2,
    'prefer-template': 1,
    'require-yield': 1,
    'template-curly-spacing': 2,
    'yield-star-spacing': 2,
  }
}
